const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";

const CHECKUSER_REQUEST = "CHECKUSER_REQUEST";
const CHECKUSER_SUCCESS = "CHECKUSER_SUCCESS";
const CHECKUSER_FAIL = "CHECKUSER_FAIL";

const LOGOUT = "LOGOUT";