export const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAIL = "GET_COURSES_FAIL";

export const GET_LIST_COURSES_REQUEST = "GET_LIST_COURSES_REQUEST";
export const GET_LIST_COURSES_SUCCESS = "GET_LIST_COURSES_SUCCESS";
export const GET_LIST_COURSES_FAIL = "GET_LIST_COURSES_FAIL";

export const INIT_STATE_COURSES = {
  isLoading: false,
  semester:null,
  course: null,
  courses: [],
};
export const GET_COURSES = "GET_COURSES";
export const GET_COURSES_SEMESTER = "GET_COURSES_SEMESTER";


export const UPDATE_COURSES_REQUEST = "UPDATE_COURSES_REQUEST";
export const UPDATE_COURSES_SUCCESS = "UPDATE_COURSES_SUCCESS";
export const UPDATE_COURSES_FAIL = "UPDATE_COURSES_FAIL";

export const CREATE_COURSES_REQUEST = "CREATE_COURSES_REQUEST";
export const CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS";
export const CREATE_COURSES_FAIL = "CREATE_COURSES_FAIL";

export const DELETE_COURSES_REQUEST = "DELETE_COURSES_REQUEST";
export const DELETE_COURSES_SUCCESS = "DELETE_COURSES_SUCCESS";
export const DELETE_COURSES_FAIL = "DELETE_COURSES_FAIL";
