export const GET_LIST_MAJOR_REQUEST = "GET_LIST_MAJOR_REQUEST";
export const GET_LIST_MAJOR_SUCCESS = "GET_LIST_MAJOR_SUCCESS";
export const GET_LIST_MAJOR_FAIL = "GET_LIST_MAJOR_FAIL";

export const GET_MAJOR = "GET_MAJOR";
export const GET_SCIENCE_MAJOR = "GET_SCIENCE_MAJOR";

export const UPDATE_MAJOR_REQUEST = "UPDATE_MAJOR_REQUEST";
export const UPDATE_MAJOR_SUCCESS = "UPDATE_MAJOR_SUCCESS";
export const UPDATE_MAJOR_FAIL = "UPDATE_MAJOR_FAIL";

export const CREATE_MAJOR_REQUEST = "CREATE_MAJOR_REQUEST";
export const CREATE_MAJOR_SUCCESS = "CREATE_MAJOR_SUCCESS";
export const CREATE_MAJOR_FAIL = "CREATE_MAJOR_FAIL";

export const DELETE_MAJOR_REQUEST = "DELETE_MAJOR_REQUEST";
export const DELETE_MAJOR_SUCCESS = "DELETE_MAJOR_SUCCESS";
export const DELETE_MAJOR_FAIL = "DELETE_MAJOR_FAIL";

export const INIT_STATE_MAJOR = {
    isLoading: false,
    science: null,
    major: null,
    majors: [],
};