export const GET_PLANSTUDY_REQUEST = "GET_PLANSTUDY_REQUEST";
export const GET_PLANSTUDY_SUCCESS = "GET_PLANSTUDY_SUCCESS";
export const GET_PLANSTUDY_FAIL = "GET_PLANSTUDY_FAIL";

export const GET_LIST_PLANSTUDY_REQUEST = "GET_LIST_PLANSTUDY_REQUEST";
export const GET_LIST_PLANSTUDY_SUCCESS = "GET_LIST_PLANSTUDY_SUCCESS";
export const GET_LIST_PLANSTUDY_FAIL = "GET_LIST_PLANSTUDY_FAIL";

export const INIT_STATE_PLANSTUDY = {
  isLoading: false,
  planstudy: null,
  planstudys: [],
};
export const GET_PLANSTUDY = "GET_PLANSTUDY";

export const UPDATE_PLANSTUDY_REQUEST = "UPDATE_PLANSTUDY_REQUEST";
export const UPDATE_PLANSTUDY_SUCCESS = "UPDATE_PLANSTUDY_SUCCESS";
export const UPDATE_PLANSTUDY_FAIL = "UPDATE_PLANSTUDY_FAIL";

export const CREATE_PLANSTUDY_REQUEST = "CREATE_PLANSTUDY_REQUEST";
export const CREATE_PLANSTUDY_SUCCESS = "CREATE_PLANSTUDY_SUCCESS";
export const CREATE_PLANSTUDY_FAIL = "CREATE_PLANSTUDY_FAIL";

export const DELETE_PLANSTUDY_REQUEST = "DELETE_PLANSTUDY_REQUEST";
export const DELETE_PLANSTUDY_SUCCESS = "DELETE_PLANSTUDY_SUCCESS";
export const DELETE_PLANSTUDY_FAIL = "DELETE_PLANSTUDY_FAIL";
