export const GET_LIST_SCIENCES_REQUEST = "GET_LIST_SCIENCES_REQUEST";
export const GET_LIST_SCIENCES_SUCCESS = "GET_LIST_SCIENCES_SUCCESS";
export const GET_LIST_SCIENCES_FAIL = "GET_LIST_SCIENCES_FAIL";

export const GET_SCIENCE = "GET_SCIENCE";

export const UPDATE_SCIENCE_REQUEST = "UPDATE_SCIENCE_REQUEST";
export const UPDATE_SCIENCE_SUCCESS = "UPDATE_SCIENCE_SUCCESS";
export const UPDATE_SCIENCE_FAIL = "UPDATE_SCIENCE_FAIL";

export const DELETE_SCIENCE_REQUEST = "DELETE_SCIENCE_REQUEST";
export const DELETE_SCIENCE_SUCCESS = "DELETE_SCIENCE_SUCCESS";
export const DELETE_SCIENCE_FAIL = "DELETE_SCIENCE_FAIL";

export const CREATE_SCIENCE_REQUEST = "CREATE_SCIENCE_REQUEST";
export const CREATE_SCIENCE_SUCCESS = "CREATE_SCIENCE_SUCCESS";
export const CREATE_SCIENCE_FAIL = "CREATE_SCIENCE_FAIL";

export const INIT_STATE_SCIENCES = {
    isLoading: false,
    error: null,
    sciences: [],
    science: null,
};