export const GET_SEMESTER_REQUEST = "GET_SEMESTER_REQUEST";
export const GET_SEMESTER_SUCCESS = "GET_SEMESTER_SUCCESS";
export const GET_SEMESTER_FAIL = "GET_SEMESTER_FAIL";

export const GET_LIST_SEMESTER_REQUEST = "GET_LIST_SEMESTER_REQUEST";
export const GET_LIST_SEMESTER_SUCCESS = "GET_LIST_SEMESTER_SUCCESS";
export const GET_LIST_SEMESTER_FAIL = "GET_LIST_SEMESTER_FAIL";

export const INIT_STATE_SEMESTER = {
  isLoading: false,
  semester: null,
  semesters: [],
};
export const GET_SEMESTER = "GET_SEMESTER";

export const UPDATE_SEMESTER_REQUEST = "UPDATE_SEMESTER_REQUEST";
export const UPDATE_SEMESTER_SUCCESS = "UPDATE_SEMESTER_SUCCESS";
export const UPDATE_SEMESTER_FAIL = "UPDATE_SEMESTER_FAIL";

export const CREATE_SEMESTER_REQUEST = "CREATE_SEMESTER_REQUEST";
export const CREATE_SEMESTER_SUCCESS = "CREATE_SEMESTER_SUCCESS";
export const CREATE_SEMESTER_FAIL = "CREATE_SEMESTER_FAIL";

export const DELETE_SEMESTER_REQUEST = "DELETE_SEMESTER_REQUEST";
export const DELETE_SEMESTER_SUCCESS = "DELETE_SEMESTER_SUCCESS";
export const DELETE_SEMESTER_FAIL = "DELETE_SEMESTER_FAIL";
