export const COURSES_LIST_REQUEST = "COURSES_LIST_REQUEST";
export const COURSES_LIST_SUCCESS = "COURSES_LIST_SUCCESS";
export const COURSES_LIST_FAIL = "COURSES_LIST_FAIL";

export const COURSES_DETAILS_REQUEST = "COURSES_DETAILS_REQUEST";
export const COURSES_DETAILS_SUCCESS = "COURSES_DETAILS_SUCCESS";
export const COURSES_DETAILS_FAIL = "COURSES_DETAILS_FAIL";
