export const COURSES_LIST_REQUEST = "COURSES_LIST_REQUEST";
export const COURSES_LIST_SUCCESS = "COURSES_LIST_SUCCESS";
export const COURSES_LIST_FAIL = "COURSES_LIST_FAIL";

export const COURSES_DETAILS_REQUEST = "COURSES_DETAILS_REQUEST";
export const COURSES_DETAILS_SUCCESS = "COURSES_DETAILS_SUCCESS";
export const COURSES_DETAILS_FAIL = "COURSES_DETAILS_FAIL";

export const CLASS_COURSES_REQUEST = "CLASS_COURSES_REQUEST";
export const CLASS_COURSES_SUCCESS = "CLASS_COURSES_SUCCESS";
export const CLASS_COURSES_FAIL = "CLASS_COURSES_FAIL";

export const CLASS_DETAILS_REQUEST = "CLASS_DETAILS_REQUEST";
export const CLASS_DETAILS_SUCCESS = "CLASS_DETAILS_SUCCESS";
export const CLASS_DETAILS_FAIL = "CLASS_DETAILS_FAIL";
