export const PROGRESS_LEARN_REQUEST = "PROGRESS_LEARN_REQUEST";
export const PROGRESS_LEARN_SUCCESS = "PROGRESS_LEARN_SUCCESS";
export const PROGRESS_LEARN_FAIL = "PROGRESS_LEARN_FAIL";
export const PROGRESS_LEARN_RESET = "PROGRESS_LEARN_RESET";
