export const LIST_RESULT_REQUEST = "LIST_RESULT_REQUEST";
export const LIST_RESULT_SUCCESS = "LIST_RESULT_SUCCESS";
export const LIST_RESULT_FAIL = "LIST_RESULT_FAIL";
export const LIST_RESULT_RESET = "LIST_RESULT_RESET";
