export const SEMESTER_LIST_REQUEST = "SEMESTER_LIST_REQUEST";
export const SEMESTER_LIST_SUCCESS = "SEMESTER_LIST_SUCCESS";
export const SEMESTER_LIST_FAIL = "SEMESTER_LIST_FAIL";
export const SEMESTER_RESET = "SEMESTER_RESET";
