export const TIMETABLE_LIST_REQUEST = "TIMETABLE_LIST_REQUEST";
export const TIMETABLE_LIST_SUCCESS = "TIMETABLE_LIST_SUCCESS";
export const TIMETABLE_LIST_FAIL = "TIMETABLE_LIST_FAIL";
export const TIMETABLE_RESET = "TIMETABLE_RESET";
