Post http://localhost:5000/auth/register
Content-Type: application/json

{
    "mssv": "18090131",
    "name":"loc",
    "email":"loc@gmail.com",
    "password": "loc123"
}

###
Post http://localhost:5000/auth/login
Content-Type: application/json

{
    "mssv": "18090131",
    "password": "loc123"
}

### 
GET http://localhost:5000/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYzNDk3NTMxNX0.7eedTNijA489ZAwx6pX-ciCpgnkByuJtgjHkEPkG1q4
### Nhận vào studentId trả về thông tin khoa, nghành của student.
GET http://localhost:5000/student/1

###
Post http://localhost:5000/course/create
Content-Type: application/json

{
    "mahocphan": "CNTT6",
    "tenhocphan":"Quan Ly Du An",
    "sotinchi":3,
    "sotiet": 45
}


### Register Course
GET http://localhost:5000/course/register/courseIds=1;2;3


### getAll Course
GET http://localhost:5000/course