###
Post http://localhost:5000/course/create
Content-Type: application/json

{
    "mahocphan": "CNTT6",
    "tenhocphan":"Quan Ly Du An",
    "sotinchi":3,
    "sotiet": 45
}


### Register Course
GET http://localhost:5000/course/register/courseIds=1;2;3


### getAll Course
GET http://localhost:5000/course