Post http://localhost:5000/auth/register
Content-Type: application/json

{
    "mssv": "18090131",
    "name":"loc",
    "email":"loc@gmail.com",
    "password": "loc123"
}

###
Post http://localhost:5000/auth/login
Content-Type: application/json

{
    "mssv": "18090131",
    "password": "loc123"
}

### 
GET http://localhost:5000/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYzNDk3NTMxNX0.7eedTNijA489ZAwx6pX-ciCpgnkByuJtgjHkEPkG1q4

